runtime: nodejs22

instance_class: F1

handlers:

- url: /assets
  static_dir: dist/web-client/browser/assets
  secure: always

- url: /(.*\.css)
  static_files: dist/web-client/browser/\1
  upload: dist/web-client/browser/(.*\.css)
  secure: always

- url: /(.*\.html)
  static_files: dist/web-client/browser/\1
  upload: dist/web-client/browser/(.*\.html)
  secure: always

- url: /(.*\.ico)
  static_files: dist/web-client/browser/\1
  upload: dist/web-client/browser/(.*\.ico)
  secure: always

- url: /(.*\.js)
  static_files: dist/web-client/browser/\1
  upload: dist/web-client/browser/(.*\.js)
  secure: always

- url: /(.*\.txt)
  static_files: dist/web-client/browser/\1
  upload: dist/web-client/browser/(.*\.txt)
  secure: always

- url: /
  static_files: dist/web-client/browser/index.html
  upload: dist/web-client/browser/index.html
  secure: always

- url: /.*
  static_files: dist/web-client/browser/index.html
  upload: dist/web-client/browser/index.html
  secure: always
